[profile.default]
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000
auto_detect_solc = true
ffi = true
fuzz = { runs = 32, max_test_rejects = 65536 }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
